#index:
#    path: /
#    controller: App\Controller\DefaultController::index


app_jm_form:
    path: /start-a-vote/form
    controller: App\Controller\StartAVote::form

app_jm_vote:
    path: /vote/{url_key}
    controller: App\Controller\Vote::form
